fields:
  TURF:
    match:
      - "H-HST"
      - "Holbrook High School"
    calendar: ${CAL_TURF}

  BROOKVILLE:
    match:
      - "H-B"
      - "Holbrook Brookville Field"
    calendar: ${CAL_BROOKVILLE}

  BUTLER:
    match:
      - "TODO-BUTLER-CODE"
    calendar: ${CAL_BUTLER}

  SUMNER:
    match:
      - "TODO-SUMNER-CODE"
    calendar: ${CAL_SUMNER}
